---
- name: delete a template
  hosts: all
  tasks:
  - name: Delete Zabbix template
    local_action:
      module: community.zabbix.zabbix_template
      server_url: http://10.201.11.7/zabbix
      login_user: Admin
      login_password: zabbix
      template_name: test_template
      state: absent
    ignore_errors: yes
...
