---
- name: import
<<<<<<< HEAD
  gather_facts: false
=======
>>>>>>> 0909eb507c2ae42777f4bd5d0c77791de12459b8
  hosts: zabbix-server
  tasks:
  - name: Import Zabbix templates from XML
    local_action:
      module: zabbix_template
      server_url: http://10.201.11.7/zabbix 
      login_user: Admin
      login_password: zabbix
      template_xml: "{{ lookup('file', 'template') }}"
      state: present
 
...
