---
- name: import
  gather_facts: false
  vars_files:
   - vars/zabbix.yml
  hosts: zabbix-server
  tasks:
  - name: restart orabbix 
    shell: /etc/init.d/orabbix restart

  - name: Import Zabbix templates from XML
    local_action:
      module: zabbix_template
      server_url: http://10.201.11.7/zabbix 
      login_user: "{{user}}"
      login_password: "{{pass}}"
      template_xml: "{{ lookup('file', '../template') }}"
      state: present
 
...
